import { GoBell } from "react-icons/go";
import { FiZap } from "react-icons/fi";
import { AiOutlineSend } from "react-icons/ai";
import { BsCheck2All } from "react-icons/bs";
import { BsCheck2 } from "react-icons/bs";
import {
  BsEmojiFrown,
  BsGear,
  BsArrowDownSquare,
  BsSearch,
  BsTelephone,
  BsCameraVideo,
  BsThreeDotsVertical,
  BsLink45Deg,
  BsMagic,
  BsTelephoneForward,
  BsTelephoneInbound,
  BsTelephoneMinus,
  BsChat,
} from "react-icons/bs";
import {
  TbPaperclip,
  TbPhoto,
  TbMicrophone,
  TbSend,
  TbCirclePlus,
  TbPlus,
  TbMessageCirclePlus,
  TbCode,
  TbLogout2,
} from "react-icons/tb";
import {
  HiOutlineHome,
  HiOutlineHeart,
  HiHeart,
  HiMiniArrowUturnRight,
  HiMiniArrowTrendingUp,
  HiMiniArrowTrendingDown,
  HiMiniCheckBadge,
  HiMiniHashtag,
  HiXMark,
} from "react-icons/hi2";

export const Icons = {
  notification: GoBell,
  flash: FiZap,
  send: AiOutlineSend,
  delivered: BsCheck2All,
  sent: BsCheck2,
  sad: BsEmojiFrown,
  settings: BsGear,
  arrowDown: BsArrowDownSquare,
  search: BsSearch,
  call: BsTelephone,
  videoCall: BsCameraVideo,
  verticalDots: BsThreeDotsVertical,
  chainLink: BsLink45Deg,
  mic: TbMicrophone,
  magic: BsMagic,
  criclePlus: TbCirclePlus,
  messageSend: TbSend,
  callSent: BsTelephoneForward,
  callRecieved: BsTelephoneInbound,
  missedCall: BsTelephoneMinus,
  clip: TbPaperclip,
  selectImage: TbPhoto,
  plus: TbPlus,
  newChat: TbMessageCirclePlus,
  code: TbCode,
  logout: TbLogout2,
  home: HiOutlineHome,
  heart: HiOutlineHeart,
  heartFilled: HiHeart,
  share: HiMiniArrowUturnRight,
  trending: HiMiniArrowTrendingUp,
  downTrend: HiMiniArrowTrendingDown,
  verified: HiMiniCheckBadge,
  hashtag: HiMiniHashtag,
  cross: HiXMark,
  chat: BsChat,
};
